services:
  terminal:
    #image: ghcr.io/m4tt72/terminal:svelte
    build: .
    container_name: terminal
    restart: unless-stopped
    ports:
      - 3010:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
